name: TnTRun
version: 1.0.1
api: 5.20.0
main: Renz\TnTRun\TnTRun
author: Renz
description: TnTRun minigame plugin for PocketMine-MP
softdepend: ["FormAPI"]
permissions:
  tntrun.command:
    default: true
    description: Allows players to use TnTRun commands
  tntrun.admin:
    default: op
    description: Allows admins to manage TnTRun arenas